language: php
sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

branches:
  only:
    - dev
    - master

script:
  - ./tests/runtests
