#!/bin/bash


if [[ $0 == '/'* ]]; then
    SCRIPT_PATH="`dirname $0`"
else
    SCRIPT_PATH="`pwd`"/"`dirname $0`"
fi


# Nice option: --testdox

phpunit --colors --stop-on-error --exclude-group disabled --verbose --bootstrap tests/test_bootstrap.php --configuration phpunit.xml $@

